ARDUINO_DIR  = /usr/share/arduino
USER_LIB_PATH = /home/pi/dev/Hippymood/cli/test/rfid/lib
ARDUINO_LIBS = SPI MFRC522

BOARD_TAG   = uno
ARDUINO_PORT = /dev/ttyUSB0

include /usr/share/arduino/Arduino.mk
